# https://github.com/marketplace/actions/cancel-workflow-action#advanced-pull-requests-from-forks
name: Cancel stale workflows
on:
  workflow_run:
    workflows: ["bench", "bench_test", "site"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: ${{ github.event.workflow.id }}
